package com.example.smite_random_picker.ui.theme

import com.example.smite_random_picker.CharacterList
import com.example.smite_random_picker.Character
import com.example.smite_random_picker.R
object SmiteGods {
    val gods = CharacterList()
    init {
        gods.addCharacter(Character("Achilles", R.drawable.achilles))
        gods.addCharacter(Character("Agni", R.drawable.agni))
        gods.addCharacter(Character("Ah Muzen Cab", R.drawable.amc))
        gods.addCharacter(Character("Ah Puch", R.drawable.ah_puch))
        gods.addCharacter(Character("Amaterasu", R.drawable.amaterasu))
        gods.addCharacter(Character("Anhur", R.drawable.anhur))
        gods.addCharacter(Character("Anubis", R.drawable.anubis))
        gods.addCharacter(Character("Ao Kuang", R.drawable.aokuang))
        gods.addCharacter(Character("Aphrodite", R.drawable.aphrodite))
        gods.addCharacter(Character("Apollo", R.drawable.apollo))
        gods.addCharacter(Character("Arachne", R.drawable.arachne))
        gods.addCharacter(Character("Ares", R.drawable.ares))
        gods.addCharacter(Character("Artemis", R.drawable.artemis))
        gods.addCharacter(Character("Artio", R.drawable.artio))
        gods.addCharacter(Character("Athena", R.drawable.athena))
        gods.addCharacter(Character("Atlas", R.drawable.atlas))
        gods.addCharacter(Character("Awilix", R.drawable.awilix))
        gods.addCharacter(Character("Baba Yaga", R.drawable.babayaga))
        gods.addCharacter(Character("Bacchus", R.drawable.bacchus))
        gods.addCharacter(Character("Bakasura", R.drawable.bakasura))
        gods.addCharacter(Character("Bake Kujira", R.drawable.bakekujira))
        gods.addCharacter(Character("Baron Samedi", R.drawable.baronsamedi))
        gods.addCharacter(Character("Bastet", R.drawable.bastet))
        gods.addCharacter(Character("Bellona", R.drawable.bellona))
        gods.addCharacter(Character("Cabrakan", R.drawable.cabrakan))
        gods.addCharacter(Character("Camazotz", R.drawable.camazotz))
        gods.addCharacter(Character("Cerberus", R.drawable.cerberus))
        gods.addCharacter(Character("Cernunnos", R.drawable.cernunnos))
        gods.addCharacter(Character("Chaac", R.drawable.chaac))
        gods.addCharacter(Character("Chang'e",  R.drawable.change))
        gods.addCharacter(Character("Charon", R.drawable.charon))
        gods.addCharacter(Character("Charybdis", R.drawable.charybdis))
        gods.addCharacter(Character("Chernobog", R.drawable.chernobog))
        gods.addCharacter(Character("Chiron", R.drawable.chiron))
        gods.addCharacter(Character("Chronos", R.drawable.chronos))
        gods.addCharacter(Character("Cliodhna", R.drawable.cliodhna))
        gods.addCharacter(Character("Cthulhu", R.drawable.cthulhu))
        gods.addCharacter(Character("Cu Chulainn", R.drawable.cuchulainn))
        gods.addCharacter(Character("Cupid", R.drawable.cupid))
        gods.addCharacter(Character("Da Ji", R.drawable.daji))
        gods.addCharacter(Character("Danzaburou", R.drawable.danzaburou))
        gods.addCharacter(Character("Discordia", R.drawable.discordia))
        gods.addCharacter(Character("Erlang Shen", R.drawable.erlangshen))
        gods.addCharacter(Character("Fafnir", R.drawable.fafnir))
        gods.addCharacter(Character("Fenrir", R.drawable.fenrir))
        gods.addCharacter(Character("Freya", R.drawable.freya))
        gods.addCharacter(Character("Ganesha", R.drawable.ganesha))
        gods.addCharacter(Character("Geb", R.drawable.geb))
        gods.addCharacter(Character("Gilgamesh", R.drawable.gilgamesh))
        gods.addCharacter(Character("Guan Yu", R.drawable.guanyu))
        gods.addCharacter(Character("Hachiman", R.drawable.hachiman))
        gods.addCharacter(Character("Hades", R.drawable.hades))
        gods.addCharacter(Character("He Bo", R.drawable.hebo))
        gods.addCharacter(Character("Heimdallr", R.drawable.heimdallr))
        gods.addCharacter(Character("Hel", R.drawable.hel))
        gods.addCharacter(Character("Hera", R.drawable.hera))
        gods.addCharacter(Character("Hercules", R.drawable.hercules))
        gods.addCharacter(Character("Horus", R.drawable.horus))
        gods.addCharacter(Character("Hou Yi", R.drawable.houyi))
        gods.addCharacter(Character("Hun Batz", R.drawable.hunbatz))
        gods.addCharacter(Character("Ishtar", R.drawable.ishtar))
        gods.addCharacter(Character("Ix Chel", R.drawable.ixchel))
        gods.addCharacter(Character("Izanami", R.drawable.izanami))
        gods.addCharacter(Character("Janus", R.drawable.janus))
        gods.addCharacter(Character("Jing Wei", R.drawable.jingwei))
        gods.addCharacter(Character("Jormungandr", R.drawable.jormungandr))
        gods.addCharacter(Character("Kali", R.drawable.kali))
        gods.addCharacter(Character("Khepri", R.drawable.khepri))
        gods.addCharacter(Character("King Arthur", R.drawable.kingarthur))
        gods.addCharacter(Character("Kukulkan", R.drawable.kukulkan))
        gods.addCharacter(Character("Kumbhakarna", R.drawable.kumbhakarna))
        gods.addCharacter(Character("Kuzenbo", R.drawable.kuzenbo))
        gods.addCharacter(Character("Lancelot", R.drawable.lancelot))
        gods.addCharacter(Character("Loki", R.drawable.loki))
        gods.addCharacter(Character("Maman Brigitte", R.drawable.mamanbrigitte))
        gods.addCharacter(Character("Martichoras", R.drawable.martichoras))
        gods.addCharacter(Character("Maui", R.drawable.maui))
        gods.addCharacter(Character("Medusa", R.drawable.medusa))
        gods.addCharacter(Character("Mercury", R.drawable.mercury))
        gods.addCharacter(Character("Merlin", R.drawable.merlin))
        gods.addCharacter(Character("Morgan Le Fay", R.drawable.morganlefay))
        gods.addCharacter(Character("Mulan", R.drawable.mulan))
        gods.addCharacter(Character("Ne Zha", R.drawable.nezha))
        gods.addCharacter(Character("Neith", R.drawable.neith))
        gods.addCharacter(Character("Nemesis", R.drawable.nemesis))
        gods.addCharacter(Character("Nike", R.drawable.nike))
        gods.addCharacter(Character("Nox", R.drawable.nox))
        gods.addCharacter(Character("Nut", R.drawable.nut))
        gods.addCharacter(Character("Nu Wa", R.drawable.nuwa))
        gods.addCharacter(Character("Odin", R.drawable.odin))
        gods.addCharacter(Character("Olorun", R.drawable.olorun))
        gods.addCharacter(Character("Osiris", R.drawable.osiris))
        gods.addCharacter(Character("Pele", R.drawable.pele))
        gods.addCharacter(Character("Persephone", R.drawable.persephone))
        gods.addCharacter(Character("Poseidon", R.drawable.poseidon))
        gods.addCharacter(Character("Ra", R.drawable.ra))
        gods.addCharacter(Character("Raijin", R.drawable.raijin))
        gods.addCharacter(Character("Rama", R.drawable.ram))
        gods.addCharacter(Character("Ratatoskr", R.drawable.ratatoskr))
        gods.addCharacter(Character("Ravana", R.drawable.ravana))
        gods.addCharacter(Character("Scylla", R.drawable.scylla))
        gods.addCharacter(Character("Serqet", R.drawable.serqet))
        gods.addCharacter(Character("Set", R.drawable.set))
        gods.addCharacter(Character("Shiva", R.drawable.shiva))
        gods.addCharacter(Character("Skadi", R.drawable.skadi))
        gods.addCharacter(Character("Sobek", R.drawable.sobek))
        gods.addCharacter(Character("Sol", R.drawable.sol))
        gods.addCharacter(Character("Sun Wukong", R.drawable.sunwukong))
        gods.addCharacter(Character("Surtr", R.drawable.surtr))
        gods.addCharacter(Character("Susano", R.drawable.susano))
        gods.addCharacter(Character("Sylvanus", R.drawable.sylvanus))
        gods.addCharacter(Character("Terra", R.drawable.terra))
        gods.addCharacter(Character("Thanatos", R.drawable.thanatos))
        gods.addCharacter(Character("The Morrigan", R.drawable.themorrigan))
        gods.addCharacter(Character("Thor", R.drawable.thor))
        gods.addCharacter(Character("Thoth", R.drawable.thoth))
        gods.addCharacter(Character("Tiamat", R.drawable.tiamat))
        gods.addCharacter(Character("Tsukuyomi", R.drawable.tsukuyomi))
        gods.addCharacter(Character("Tyr", R.drawable.tyr))
        gods.addCharacter(Character("Ullr", R.drawable.ullr))
        gods.addCharacter(Character("Vamana", R.drawable.vamana))
        gods.addCharacter(Character("Vulcan", R.drawable.vulcan))
        gods.addCharacter(Character("Xbalanque", R.drawable.xbalanque))
        gods.addCharacter(Character("Xing Tian", R.drawable.xingtian))
        gods.addCharacter(Character("Yemoja", R.drawable.yemoja))
        gods.addCharacter(Character("Ymir", R.drawable.ymir))
        gods.addCharacter(Character("Yu Huang", R.drawable.yuhuang))
        gods.addCharacter(Character("Zeus", R.drawable.zeus))
        gods.addCharacter(Character("Zhong Kui", R.drawable.zhongkui))
    }
}
